# Generated by Django 5.2.6 on 2025-10-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('hq_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('fare', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='Airline.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing', to='Airline.airport')),
            ],
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_first_name', models.CharField(max_length=100)),
                ('passenger_last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=8)),
                ('address', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('passport_no', models.CharField(max_length=100)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.flight')),
                ('seatclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.seatclass')),
            ],
        ),
    ]
