# Generated by Django 5.2.6 on 2025-10-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0003_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seatclass',
            field=models.ForeignKey(choices=[('Economy', 'Economy class'), ('Business', 'Business class'), ('First Class', 'First Class')], on_delete=django.db.models.deletion.CASCADE, to='Airline.seatclass'),
        ),
    ]
