# Generated by Django 5.2.6 on 2025-10-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0004_alter_passenger_seatclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seatclass',
            field=models.ForeignKey(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class')], on_delete=django.db.models.deletion.CASCADE, to='Airline.seatclass'),
        ),
    ]
