# Generated by Django 5.2.6 on 2025-10-15 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0005_alter_passenger_seatclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seatclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.seatclass'),
        ),
    ]
