# Generated by Django 5.2.6 on 2025-10-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0006_alter_passenger_seatclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatclass',
            name='seat_type',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class')], default='E', max_length=50),
            preserve_default=False,
        ),
    ]
