# Generated by Django 5.2.6 on 2025-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0007_seatclass_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatclass',
            name='seat_type',
            field=models.CharField(choices=[('ECON', 'Economy'), ('BUSN', 'Business'), ('FIRST', 'First Class')], max_length=50),
        ),
    ]
