# Generated by Django 5.2.6 on 2025-10-25 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0010_alter_seatclass_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^\\d{10}$')]),
        ),
    ]
