# Generated by Django 5.2.6 on 2025-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0011_alter_airplane_capacity_alter_passenger_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PASSENGER', 'Passenger')], default='PASSENGER', max_length=10),
        ),
    ]
