# Generated by Django 5.2.6 on 2025-11-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0012_passenger_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PASSENGER', 'Passenger')], default='ADMIN', max_length=10),
        ),
    ]
